"""empty message

Revision ID: e3d5d0dec3f4
Revises: 
Create Date: 2023-02-02 00:47:33.222139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d5d0dec3f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=55), nullable=False),
    sa.Column('email', sa.String(length=55), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', 'EXTRA_LARGE', name='sizes'), nullable=True),
    sa.Column('flavour', sa.String(length=55), nullable=False),
    sa.Column('order_status', sa.Enum('PENDING', 'ON_THE_WAY', 'DELIVERED', name='status'), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('customer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('users')
    # ### end Alembic commands ###
